using Microsoft.AspNetCore.Mvc;
using Bogus;
using API.Data;
using API.Models;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using System.Text;

namespace API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SeedController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public SeedController(ApplicationDbContext context)
        {
            _context = context;
        }

        private static string HashPassword(string password)
        {
            using var sha256 = SHA256.Create();
            var hashedBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
            return Convert.ToBase64String(hashedBytes);
        }

        [HttpPost("generate")]
        public async Task<IActionResult> GenerateTestData(int count = 10)
        {
            try
            {
                // 1. Ensure at least 2 Universities exist
                var university1 = await _context.Universities.FirstOrDefaultAsync(u => u.UniversityName == "Apex National University");
                if (university1 == null)
                {
                    university1 = new University { UniversityName = "Apex National University", IsActive = true };
                    _context.Universities.Add(university1);
                }

                var university2 = await _context.Universities.FirstOrDefaultAsync(u => u.UniversityName == "Global Tech University");
                if (university2 == null)
                {
                    university2 = new University { UniversityName = "Global Tech University", IsActive = true };
                    _context.Universities.Add(university2);
                }

                await _context.SaveChangesAsync();

                var universities = new List<University> { university1, university2 };

                // 2. Ensure Admin User exists
                var adminUser = await _context.Users.FirstOrDefaultAsync(u => u.Email == "admin@osm.com");
                if (adminUser == null)
                {
                    adminUser = new User
                    {
                        Name = "System Administrator",
                        Email = "admin@osm.com",
                        PasswordHash = HashPassword("Admin@123"),
                        AutoGeneratedPassword = "Admin@123",
                        UserType = "admin",
                        UniversityId = university1.UniversityId,
                        IsActive = true,
                        IsApproved = true,
                        Phone = "+1-555-0100",
                        Address = "100 Admin Blvd, Headquarters",
                        ProfileImage = ""
                    };
                    _context.Users.Add(adminUser);
                }

                // 3. Ensure Coordinator Users exist for each university
                var coordinator1 = await _context.Users.FirstOrDefaultAsync(u => u.Email == "coordinator1@osm.com");
                if (coordinator1 == null)
                {
                    coordinator1 = new User
                    {
                        Name = "Apex Coordinator",
                        Email = "coordinator1@osm.com",
                        PasswordHash = HashPassword("Coordinator@123"),
                        AutoGeneratedPassword = "Coordinator@123",
                        UserType = "coordinator",
                        UniversityId = university1.UniversityId,
                        IsActive = true,
                        IsApproved = true,
                        Phone = "+1-555-0101",
                        Address = "Apex University Campus, Block A",
                        ProfileImage = ""
                    };
                    _context.Users.Add(coordinator1);
                }

                var coordinator2 = await _context.Users.FirstOrDefaultAsync(u => u.Email == "coordinator2@osm.com");
                if (coordinator2 == null)
                {
                    coordinator2 = new User
                    {
                        Name = "Global Coordinator",
                        Email = "coordinator2@osm.com",
                        PasswordHash = HashPassword("Coordinator@123"),
                        AutoGeneratedPassword = "Coordinator@123",
                        UserType = "coordinator",
                        UniversityId = university2.UniversityId,
                        IsActive = true,
                        IsApproved = true,
                        Phone = "+1-555-0102",
                        Address = "Global Tech Campus, Main Office",
                        ProfileImage = ""
                    };
                    _context.Users.Add(coordinator2);
                }

                await _context.SaveChangesAsync();

                // 4. Ensure Default Roles exist
                var allPermissions = new List<string>
                {
                    "CREATE_UNIVERSITY", "READ_UNIVERSITY", "UPDATE_UNIVERSITY", "DELETE_UNIVERSITY",
                    "CREATE_COLLEGE", "READ_COLLEGE", "UPDATE_COLLEGE", "DELETE_COLLEGE",
                    "CREATE_DEPARTMENT", "READ_DEPARTMENT", "UPDATE_DEPARTMENT", "DELETE_DEPARTMENT",
                    "CREATE_COURSE", "READ_COURSE", "UPDATE_COURSE", "DELETE_COURSE",
                    "CREATE_SUBJECT", "READ_SUBJECT", "UPDATE_SUBJECT", "DELETE_SUBJECT",
                    "CREATE_SESSION", "READ_SESSION", "UPDATE_SESSION", "DELETE_SESSION",
                    "CREATE_PROJECT", "READ_PROJECT", "UPDATE_PROJECT", "DELETE_PROJECT",
                    "CREATE_PAPER", "READ_PAPER", "UPDATE_PAPER", "DELETE_PAPER",
                    "IMPORT_PAPERS", "MANAGE_SECTIONS", "MANAGE_QUESTIONS",
                    "CREATE_SCRIPT", "READ_SCRIPT", "UPDATE_SCRIPT", "DELETE_SCRIPT",
                    "CREATE_ALLOCATION", "READ_ALLOCATION", "UPDATE_ALLOCATION", "DELETE_ALLOCATION",
                    "CREATE_MARKING", "READ_MARKING", "UPDATE_MARKING", "DELETE_MARKING",
                    "CREATE_ATTENDANCE", "READ_ATTENDANCE", "UPDATE_ATTENDANCE", "DELETE_ATTENDANCE",
                    "CREATE_USER", "READ_USER", "UPDATE_USER", "DELETE_USER", "INVITE_USER",
                    "CREATE_ROLE", "READ_ROLE", "UPDATE_ROLE", "DELETE_ROLE",
                    "VIEW_REPORTS", "EXPORT_REPORTS",
                    "VIEW_LOGS", "MANAGE_SETTINGS", "VIEW_ANALYTICS"
                };

                var defaultRoles = new List<Role>
                {
                    new Role
                    {
                        RoleName = "Admin",
                        Description = "Full system access and administrator privileges",
                        HierarchyLevel = 1,
                        IsActive = true,
                        PermissionsList = allPermissions
                    },
                    new Role
                    {
                        RoleName = "Coordinator",
                        Description = "Manages exam evaluations, scripts, departments, courses, and examiner allocations",
                        HierarchyLevel = 2,
                        IsActive = true,
                        PermissionsList = new List<string>
                        {
                            "READ_UNIVERSITY", "READ_COLLEGE",
                            "CREATE_DEPARTMENT", "READ_DEPARTMENT", "UPDATE_DEPARTMENT",
                            "CREATE_COURSE", "READ_COURSE", "UPDATE_COURSE",
                            "CREATE_SUBJECT", "READ_SUBJECT", "UPDATE_SUBJECT",
                            "CREATE_SESSION", "READ_SESSION", "UPDATE_SESSION",
                            "CREATE_PROJECT", "READ_PROJECT", "UPDATE_PROJECT",
                            "CREATE_PAPER", "READ_PAPER", "UPDATE_PAPER", "IMPORT_PAPERS", "MANAGE_SECTIONS", "MANAGE_QUESTIONS",
                            "CREATE_SCRIPT", "READ_SCRIPT", "UPDATE_SCRIPT",
                            "CREATE_ALLOCATION", "READ_ALLOCATION", "UPDATE_ALLOCATION", "DELETE_ALLOCATION",
                            "READ_MARKING", "CREATE_MARKING", "UPDATE_MARKING",
                            "READ_ATTENDANCE", "CREATE_ATTENDANCE", "UPDATE_ATTENDANCE",
                            "READ_USER", "INVITE_USER", "READ_ROLE",
                            "VIEW_REPORTS", "EXPORT_REPORTS", "VIEW_LOGS"
                        }
                    },
                    new Role
                    {
                        RoleName = "Examiner",
                        Description = "Evaluates assigned answer scripts and submits marks",
                        HierarchyLevel = 3,
                        IsActive = true,
                        PermissionsList = new List<string>
                        {
                            "READ_SUBJECT", "READ_PAPER", "READ_SCRIPT", "READ_MARKING", "CREATE_MARKING", "UPDATE_MARKING", "VIEW_REPORTS", "READ_ALLOCATION"
                        }
                    },
                    new Role
                    {
                        RoleName = "Operator",
                        Description = "Scans answer booklets, manages queues, and handles document ingestion",
                        HierarchyLevel = 4,
                        IsActive = true,
                        PermissionsList = new List<string>
                        {
                            "READ_PAPER", "CREATE_SCRIPT", "READ_SCRIPT", "UPDATE_SCRIPT"
                        }
                    },
                    new Role
                    {
                        RoleName = "Viewer",
                        Description = "Read-only access to view exam reports and statistics",
                        HierarchyLevel = 5,
                        IsActive = true,
                        PermissionsList = new List<string>
                        {
                            "READ_PAPER", "READ_SCRIPT", "VIEW_REPORTS"
                        }
                    }
                };

                foreach (var role in defaultRoles)
                {
                    var existing = await _context.Roles.FirstOrDefaultAsync(r => r.RoleName.ToLower() == role.RoleName.ToLower());
                    if (existing == null)
                    {
                        _context.Roles.Add(role);
                    }
                    else if (existing.RoleName.Equals("Admin", StringComparison.OrdinalIgnoreCase))
                    {
                        existing.PermissionsList = allPermissions;
                    }
                }
                await _context.SaveChangesAsync();

                // 5. Ensure at least one Session exists
                var session = await _context.Sessions.FirstOrDefaultAsync();
                if (session == null)
                {
                    session = new Session { SessionName = "Academic Session 2026-2027", IsActive = true };
                    _context.Sessions.Add(session);
                    await _context.SaveChangesAsync();
                }

                // 5. Generate Fake Departments for universities
                var allDepartments = new List<Department>();
                var departmentFaker = new Faker<Department>()
                    .RuleFor(d => d.Name, f => f.Commerce.Department() + " " + f.Random.AlphaNumeric(3).ToUpper())
                    .RuleFor(d => d.IsActive, true);

                foreach (var uni in universities)
                {
                    var uniDepts = departmentFaker.Clone()
                        .RuleFor(d => d.UniversityId, uni.UniversityId)
                        .Generate(2);
                    allDepartments.AddRange(uniDepts);
                }
                _context.Departments.AddRange(allDepartments);
                await _context.SaveChangesAsync();

                // 6. Generate Fake Courses
                var courseFaker = new Faker<Courses>()
                    .RuleFor(c => c.Name, f => f.Company.CatchPhrase() + " " + f.Random.AlphaNumeric(3).ToUpper())
                    .RuleFor(c => c.Type, f => f.PickRandom(new[] { "Undergraduate", "Postgraduate", "Diploma" }))
                    .RuleFor(c => c.IsActive, true);

                var courses = new List<Courses>();
                foreach (var dept in allDepartments)
                {
                    var deptCourses = courseFaker.Generate(2);
                    courses.AddRange(deptCourses);
                }
                _context.Courses.AddRange(courses);
                await _context.SaveChangesAsync();

                var mappings = new List<DepartmentCourse>();
                int courseIndex = 0;
                foreach (var dept in departments)
                {
                    for (int i = 0; i < 2; i++)
                    {
                        mappings.Add(new DepartmentCourse { DepartmentId = dept.DepartmentId, CourseId = courses[courseIndex].Id });
                        courseIndex++;
                    }
                }
                _context.DepartmentCourses.AddRange(mappings);
                await _context.SaveChangesAsync();

                // 3. Generate Fake Subjects
                var subjectFaker = new Faker<Subject>()
                    .RuleFor(s => s.SubName, f => f.Commerce.ProductName())
                    .RuleFor(s => s.SubCode, f => f.Random.AlphaNumeric(6).ToUpper())
                    .RuleFor(s => s.Status, true);
                var subjects = subjectFaker.Generate(10);
                _context.Subjects.AddRange(subjects);
                await _context.SaveChangesAsync();

                // 8. Generate Fake Projects
                var projects = new List<Project>();
                var projectFaker = new Faker<Project>()
                    .RuleFor(p => p.ProjectName, f => f.Commerce.Department() + " Examination")
                    .RuleFor(p => p.SessionId, session.SessionId)
                    .RuleFor(p => p.IsActive, true);

                foreach (var uni in universities)
                {
                    var uniProjects = projectFaker.Clone()
                        .RuleFor(p => p.UniversityId, uni.UniversityId)
                        .Generate(2);
                    projects.AddRange(uniProjects);
                }
                _context.Projects.AddRange(projects);
                await _context.SaveChangesAsync();

                // 9. Generate Fake Papers
                var papers = new List<Paper>();
                var paperFaker = new Faker<Paper>()
                    .RuleFor(p => p.PaperCode, f => f.Random.AlphaNumeric(6).ToUpper())
                    .RuleFor(p => p.PaperName, f => f.Company.CatchPhrase())
                    .RuleFor(p => p.PaperNumber, f => f.Random.Int(1, 10))
                    .RuleFor(p => p.MaxMarks, f => f.Random.Int(50, 100))
                    .RuleFor(p => p.TotalQuestions, f => f.Random.Int(10, 30))
                    .RuleFor(p => p.Description, f => f.Lorem.Sentence())
                    .RuleFor(p => p.IsActive, true);

                foreach (var uni in universities)
                {
                    var uniPapers = paperFaker.Clone()
                        .RuleFor(p => p.UniversityId, uni.UniversityId)
                        .Generate(3);
                    papers.AddRange(uniPapers);
                }
                _context.Papers.AddRange(papers);
                await _context.SaveChangesAsync();

                // 10. Generate Fake ProjectPapers
                var projectPapers = new List<ProjectPaper>();
                foreach (var project in projects)
                {
                    var uniPapers = papers.Where(p => p.UniversityId == project.UniversityId).Take(2);
                    foreach (var paper in uniPapers)
                    {
                        projectPapers.Add(new ProjectPaper
                        {
                            ProjectId = project.ProjectId,
                            PaperId = paper.PaperId,
                            CatchNo = new Faker().Random.AlphaNumeric(4).ToUpper(),
                            IsActive = true
                        });
                    }
                }
                _context.ProjectPapers.AddRange(projectPapers);
                await _context.SaveChangesAsync();

                // 11. Generate Fake Scripts
                var scriptFaker = new Faker<Script>()
                    .RuleFor(s => s.InBuiltBarcode, f => f.Random.AlphaNumeric(10))
                    .RuleFor(s => s.GeneratedBarcode, f => f.Random.AlphaNumeric(10))
                    .RuleFor(s => s.CleanPdfUrl, f => "https://example.com/sample.pdf")
                    .RuleFor(s => s.Status, f => f.PickRandom(new[] { "pending", "in_progress", "completed" }))
                    .RuleFor(s => s.RollNumber, f => f.Random.Number(100000, 999999).ToString());

                var scripts = new List<Script>();
                foreach (var pp in projectPapers)
                {
                    var ppScripts = scriptFaker.Clone()
                        .RuleFor(s => s.ProjectPaperId, pp.Id)
                        .Generate(count);
                    scripts.AddRange(ppScripts);
                }
                _context.Scripts.AddRange(scripts);
                await _context.SaveChangesAsync();

                return Ok(new
                {
                    Message = "Test data generated successfully",
                    Universities = universities.Select(u => new { u.UniversityId, u.UniversityName }),
                    AdminUser = new { adminUser.Email, Role = adminUser.UserType, DefaultPassword = "Admin@123" },
                    Coordinators = new[]
                    {
                        new { coordinator1.Email, Role = coordinator1.UserType, UniversityId = coordinator1.UniversityId, DefaultPassword = "Coordinator@123" },
                        new { coordinator2.Email, Role = coordinator2.UserType, UniversityId = coordinator2.UniversityId, DefaultPassword = "Coordinator@123" }
                    },
                    DepartmentsCreated = allDepartments.Count,
                    CoursesCreated = courses.Count,
                    SubjectsCreated = subjects.Count,
                    ProjectsCreated = projects.Count,
                    PapersCreated = papers.Count,
                    ProjectPapersCreated = projectPapers.Count,
                    ScriptsCreated = scripts.Count
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { Message = "Failed to generate test data", Error = ex.Message, InnerError = ex.InnerException?.Message });
            }
        }
    }
}
