// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.Models.Allocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExaminerId")
                        .HasColumnType("int");

                    b.Property<int>("ScriptId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TimeTakenSeconds")
                        .HasColumnType("int");

                    b.HasKey("AllocationId");

                    b.HasIndex("ExaminerId");

                    b.HasIndex("ScriptId");

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("API.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExaminerId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("ExaminerId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("API.Models.BarcodeConfiguration", b =>
                {
                    b.Property<int>("BarcodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BarcodeId");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Barcode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Prefix")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("prefix");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Status");

                    b.Property<string>("SubjectCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("subject_code");

                    b.Property<string>("Suffix")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("suffix");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("BarcodeId");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("SubjectCode");

                    b.ToTable("barcode_configuration");
                });

            modelBuilder.Entity("API.Models.Booklet", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("CandidateRef")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("candidate_ref");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalPagesExpected")
                        .HasColumnType("int")
                        .HasColumnName("total_pages_expected");

                    b.Property<int>("TotalPagesReceived")
                        .HasColumnType("int")
                        .HasColumnName("total_pages_received");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("booklets");
                });

            modelBuilder.Entity("API.Models.BookletConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("config_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("IntegrationPath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("integration_path");

                    b.Property<float>("RoiXEnd")
                        .HasColumnType("float")
                        .HasColumnName("roi_x_end");

                    b.Property<float>("RoiXStart")
                        .HasColumnType("float")
                        .HasColumnName("roi_x_start");

                    b.Property<float>("RoiYEnd")
                        .HasColumnType("float")
                        .HasColumnName("roi_y_end");

                    b.Property<float>("RoiYStart")
                        .HasColumnType("float")
                        .HasColumnName("roi_y_start");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int")
                        .HasColumnName("total_pages");

                    b.HasKey("Id");

                    b.ToTable("booklet_configs");
                });

            modelBuilder.Entity("API.Models.College", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CollegeCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CollegeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CollegeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Colleges");
                });

            modelBuilder.Entity("API.Models.CourseSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("CourseId", "SubjectId")
                        .IsUnique();

                    b.ToTable("CourseSubjects");
                });

            modelBuilder.Entity("API.Models.Courses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "Name")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("API.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("UniversityId", "Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("API.Models.DepartmentSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("DepartmentSubjects");
                });

            modelBuilder.Entity("API.Models.ErrorLog", b =>
                {
                    b.Property<int>("ErrorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OccuranceSpace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ErrorID");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("API.Models.EventLog", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EventTriggeredBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EventID");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("API.Models.ExamBatch", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("exam_code");

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("exam_date");

                    b.Property<string>("ExamTitle")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("exam_title");

                    b.Property<int?>("ExpectedBookletCount")
                        .HasColumnType("int")
                        .HasColumnName("expected_booklet_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("exam_batches");
                });

            modelBuilder.Entity("API.Models.ExaminerExpertise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExaminerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("ExaminerId", "SubjectId")
                        .IsUnique();

                    b.ToTable("ExaminerExpertises");
                });

            modelBuilder.Entity("API.Models.GeneratedPdf", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("BookletId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("booklet_id");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at");

                    b.Property<int>("PageCount")
                        .HasColumnType("int")
                        .HasColumnName("page_count");

                    b.Property<string>("PdfPath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pdf_path");

                    b.Property<string>("Sha256Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sha256_checksum");

                    b.Property<string>("XmpMetadata")
                        .HasColumnType("longtext")
                        .HasColumnName("xmp_metadata");

                    b.HasKey("Id");

                    b.HasIndex("BookletId");

                    b.ToTable("generated_pdfs");
                });

            modelBuilder.Entity("API.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("API.Models.Marking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AllocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EvaluatedPdfUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExaminerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ScriptId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalMarks")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId");

                    b.HasIndex("ExaminerId");

                    b.HasIndex("ScriptId");

                    b.ToTable("Markings");
                });

            modelBuilder.Entity("API.Models.Operator", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("WorkstationId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.ToTable("operators");
                });

            modelBuilder.Entity("API.Models.PageEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("EventDetail")
                        .HasColumnType("longtext")
                        .HasColumnName("event_detail");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("PageId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("page_id");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("page_events");
                });

            modelBuilder.Entity("API.Models.Paper", b =>
                {
                    b.Property<int>("PaperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MaxMarks")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PaperCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PaperName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PaperNumber")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PaperId");

                    b.HasIndex("UniversityId");

                    b.HasIndex("PaperCode", "UniversityId")
                        .IsUnique();

                    b.ToTable("Papers");
                });

            modelBuilder.Entity("API.Models.PaperExaminer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExaminerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxScriptLimit")
                        .HasColumnType("int");

                    b.Property<int>("PaperId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExaminerId");

                    b.HasIndex("PaperId", "ExaminerId")
                        .IsUnique();

                    b.ToTable("PaperExaminers");
                });

            modelBuilder.Entity("API.Models.PdfRecord", b =>
                {
                    b.Property<int>("PdfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Pdf_Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("GeneratedBarcode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("generated_barcode");

                    b.Property<string>("InbuiltBarcode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("inbuilt_barcode");

                    b.Property<string>("PdfLocation")
                        .HasColumnType("longtext")
                        .HasColumnName("pdf_location");

                    b.Property<string>("PdfName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pdf_name");

                    b.HasKey("PdfId");

                    b.HasIndex("GeneratedBarcode");

                    b.ToTable("pdf_records");
                });

            modelBuilder.Entity("API.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("API.Models.ProjectConfiguration", b =>
                {
                    b.Property<int>("ProjectConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjectConfigId");

                    b.Property<int?>("BarcodeId")
                        .HasColumnType("int")
                        .HasColumnName("BarcodeId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("EnableManualCorrection")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enable_manual_correction");

                    b.Property<bool>("EnableOcrValidation")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enable_ocr_validation");

                    b.Property<string>("InputFolder")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("input_folder");

                    b.Property<string>("OutputFolder")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("output_folder");

                    b.Property<string>("PaperCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PaperCode");

                    b.Property<int?>("PaperId")
                        .HasColumnType("int")
                        .HasColumnName("PaperId");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("ProjectId");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("TemplateId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("ProjectConfigId");

                    b.HasIndex("BarcodeId");

                    b.HasIndex("PaperId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TemplateId");

                    b.ToTable("project_configuration");
                });

            modelBuilder.Entity("API.Models.ProjectPaper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CatchNo")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PaperId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionPaperPdfUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.HasIndex("ProjectId", "PaperId")
                        .IsUnique();

                    b.ToTable("ProjectPapers");
                });

            modelBuilder.Entity("API.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Marks")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("OptionalGroupCode")
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("QuestionId");

                    b.HasIndex("SectionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("API.Models.QuestionMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAttempted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MarkingId")
                        .HasColumnType("int");

                    b.Property<decimal>("MarksAwarded")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarkingId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionMarks");
                });

            modelBuilder.Entity("API.Models.QuestionType", b =>
                {
                    b.Property<int>("QuestionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuestiontypeId");

                    b.Property<string>("QuestionTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Questiontype");

                    b.HasKey("QuestionTypeId");

                    b.ToTable("questiontypes");
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("API.Models.ScanSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("BookletConfigId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("booklet_config_id");

                    b.Property<string>("CandidateRef")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("candidate_ref");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<string>("ExamBatchId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("exam_batch_id");

                    b.Property<string>("IntegrationPath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("integration_path");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("operator_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BookletConfigId");

                    b.HasIndex("ExamBatchId");

                    b.HasIndex("OperatorId");

                    b.ToTable("scan_sessions");
                });

            modelBuilder.Entity("API.Models.ScannedPage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("BookletId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("booklet_id");

                    b.Property<int?>("DetectedPageNumber")
                        .HasColumnType("int")
                        .HasColumnName("detected_page_number");

                    b.Property<string>("DetectionSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("detection_source");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<int?>("ManualPageNumber")
                        .HasColumnType("int")
                        .HasColumnName("manual_page_number");

                    b.Property<int?>("OcrConfidence")
                        .HasColumnType("int")
                        .HasColumnName("ocr_confidence");

                    b.Property<DateTime?>("ScannedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("scanned_at");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("BookletId");

                    b.HasIndex("SessionId");

                    b.ToTable("scanned_pages");
                });

            modelBuilder.Entity("API.Models.Script", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CleanPdfUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeneratedBarcode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("InBuiltBarcode")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsReEvaluationRequested")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProjectPaperId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("RollNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("TotalMarks")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedBarcode")
                        .IsUnique();

                    b.HasIndex("ProjectPaperId");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("API.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EndQuestion")
                        .HasColumnType("int");

                    b.Property<int>("MaxQuestionsToAttempt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PaperId")
                        .HasColumnType("int");

                    b.Property<int?>("SectionMasterId")
                        .HasColumnType("int");

                    b.Property<int>("StartQuestion")
                        .HasColumnType("int");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.HasIndex("SectionMasterId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("API.Models.SectionMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EndQuestion")
                        .HasColumnType("int");

                    b.Property<int>("MaxQuestionsToAttempt")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("StartQuestion")
                        .HasColumnType("int");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SectionMasters");
                });

            modelBuilder.Entity("API.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SessionId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("API.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SubCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("API.Models.SubjectPaper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaperId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectPapers");
                });

            modelBuilder.Entity("API.Models.TemplateConfiguration", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    b.Property<string>("BarcodeAvailability")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("barcode_availability");

                    b.Property<string>("BarcodeDimensions")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("barcode_dimensions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("HasBarcode")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_barcode");

                    b.Property<bool>("HasPageNumber")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_page_number");

                    b.Property<string>("PageDimension")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("page_dimension");

                    b.Property<string>("PageNoPosition")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("page_no_position");

                    b.Property<string>("PageRange")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("page_range");

                    b.Property<int>("SkipPages")
                        .HasColumnType("int")
                        .HasColumnName("skip_pages");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("template_name");

                    b.Property<int?>("TotalPages")
                        .HasColumnType("int")
                        .HasColumnName("total_pages");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("TemplateId");

                    b.HasIndex("SkipPages");

                    b.HasIndex("Status");

                    b.ToTable("template_configuration");
                });

            modelBuilder.Entity("API.Models.University", b =>
                {
                    b.Property<int>("UniversityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UniversityId");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("API.Models.UploadQueue", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastAttemptedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_attempted_at");

                    b.Property<string>("LastError")
                        .HasColumnType("longtext")
                        .HasColumnName("last_error");

                    b.Property<string>("PdfId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("pdf_id");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("queued_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("retry_count");

                    b.Property<string>("ServerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("server_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("PdfId");

                    b.ToTable("upload_queue");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AadharNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AutoGeneratedPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CollegeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<string>("Experience")
                        .HasColumnType("longtext");

                    b.Property<string>("Fname")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PanNo")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SubjectId1")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId2")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId3")
                        .HasColumnType("int");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UniversityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Models.Allocation", b =>
                {
                    b.HasOne("API.Models.User", "Examiner")
                        .WithMany("Allocations")
                        .HasForeignKey("ExaminerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Script", "Script")
                        .WithMany("Allocations")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examiner");

                    b.Navigation("Script");
                });

            modelBuilder.Entity("API.Models.Attendance", b =>
                {
                    b.HasOne("API.Models.User", "Examiner")
                        .WithMany()
                        .HasForeignKey("ExaminerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examiner");
                });

            modelBuilder.Entity("API.Models.Booklet", b =>
                {
                    b.HasOne("API.Models.ScanSession", "ScanSession")
                        .WithMany("Booklets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanSession");
                });

            modelBuilder.Entity("API.Models.CourseSubject", b =>
                {
                    b.HasOne("API.Models.Courses", "Course")
                        .WithMany("CourseSubjects")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Subject", "Subject")
                        .WithMany("CourseSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("API.Models.Courses", b =>
                {
                    b.HasOne("API.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("API.Models.Department", b =>
                {
                    b.HasOne("API.Models.University", "University")
                        .WithMany("Departments")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("API.Models.DepartmentSubject", b =>
                {
                    b.HasOne("API.Models.Department", "Department")
                        .WithMany("DepartmentSubjects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Subject", "Subject")
                        .WithMany("DepartmentSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("API.Models.ExaminerExpertise", b =>
                {
                    b.HasOne("API.Models.User", "Examiner")
                        .WithMany("Expertise")
                        .HasForeignKey("ExaminerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Subject", "Subject")
                        .WithMany("ExaminerExpertises")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examiner");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("API.Models.GeneratedPdf", b =>
                {
                    b.HasOne("API.Models.Booklet", "Booklet")
                        .WithMany("GeneratedPdfs")
                        .HasForeignKey("BookletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booklet");
                });

            modelBuilder.Entity("API.Models.Invitation", b =>
                {
                    b.HasOne("API.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("University");
                });

            modelBuilder.Entity("API.Models.Marking", b =>
                {
                    b.HasOne("API.Models.Allocation", "Allocation")
                        .WithMany()
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.User", "Examiner")
                        .WithMany("Markings")
                        .HasForeignKey("ExaminerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Script", "Script")
                        .WithMany("Markings")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allocation");

                    b.Navigation("Examiner");

                    b.Navigation("Script");
                });

            modelBuilder.Entity("API.Models.PageEvent", b =>
                {
                    b.HasOne("API.Models.ScannedPage", "ScannedPage")
                        .WithMany("PageEvents")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedPage");
                });

            modelBuilder.Entity("API.Models.Paper", b =>
                {
                    b.HasOne("API.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId");

                    b.Navigation("University");
                });

            modelBuilder.Entity("API.Models.PaperExaminer", b =>
                {
                    b.HasOne("API.Models.User", "Examiner")
                        .WithMany()
                        .HasForeignKey("ExaminerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Paper", "Paper")
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examiner");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("API.Models.Project", b =>
                {
                    b.HasOne("API.Models.Session", "Session")
                        .WithMany("Projects")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.University", "University")
                        .WithMany("Projects")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("University");
                });

            modelBuilder.Entity("API.Models.ProjectConfiguration", b =>
                {
                    b.HasOne("API.Models.BarcodeConfiguration", "BarcodeConfiguration")
                        .WithMany()
                        .HasForeignKey("BarcodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.Models.Paper", "Paper")
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.Models.TemplateConfiguration", "TemplateConfiguration")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BarcodeConfiguration");

                    b.Navigation("Paper");

                    b.Navigation("Project");

                    b.Navigation("Subject");

                    b.Navigation("TemplateConfiguration");
                });

            modelBuilder.Entity("API.Models.ProjectPaper", b =>
                {
                    b.HasOne("API.Models.Paper", "Paper")
                        .WithMany("ProjectPapers")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Project", "Project")
                        .WithMany("ProjectPapers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("API.Models.Question", b =>
                {
                    b.HasOne("API.Models.Section", "Section")
                        .WithMany("Questions")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("API.Models.QuestionMark", b =>
                {
                    b.HasOne("API.Models.Marking", "Marking")
                        .WithMany("QuestionMarks")
                        .HasForeignKey("MarkingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Question", "Question")
                        .WithMany("QuestionMarks")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marking");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("API.Models.ScanSession", b =>
                {
                    b.HasOne("API.Models.BookletConfig", "BookletConfig")
                        .WithMany("ScanSessions")
                        .HasForeignKey("BookletConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.ExamBatch", "ExamBatch")
                        .WithMany("ScanSessions")
                        .HasForeignKey("ExamBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Operator", "Operator")
                        .WithMany("ScanSessions")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookletConfig");

                    b.Navigation("ExamBatch");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("API.Models.ScannedPage", b =>
                {
                    b.HasOne("API.Models.Booklet", "Booklet")
                        .WithMany("ScannedPages")
                        .HasForeignKey("BookletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.ScanSession", "ScanSession")
                        .WithMany("ScannedPages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booklet");

                    b.Navigation("ScanSession");
                });

            modelBuilder.Entity("API.Models.Script", b =>
                {
                    b.HasOne("API.Models.ProjectPaper", "ProjectPaper")
                        .WithMany("Scripts")
                        .HasForeignKey("ProjectPaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectPaper");
                });

            modelBuilder.Entity("API.Models.Section", b =>
                {
                    b.HasOne("API.Models.Paper", "Paper")
                        .WithMany("Sections")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.SectionMaster", "SectionMaster")
                        .WithMany()
                        .HasForeignKey("SectionMasterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Paper");

                    b.Navigation("SectionMaster");
                });

            modelBuilder.Entity("API.Models.SubjectPaper", b =>
                {
                    b.HasOne("API.Models.Paper", "Paper")
                        .WithMany("SubjectPapers")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Subject", "Subject")
                        .WithMany("SubjectPapers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("API.Models.UploadQueue", b =>
                {
                    b.HasOne("API.Models.GeneratedPdf", "GeneratedPdf")
                        .WithMany("UploadQueues")
                        .HasForeignKey("PdfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedPdf");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.HasOne("API.Models.University", "University")
                        .WithMany("Users")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("University");
                });

            modelBuilder.Entity("API.Models.Booklet", b =>
                {
                    b.Navigation("GeneratedPdfs");

                    b.Navigation("ScannedPages");
                });

            modelBuilder.Entity("API.Models.BookletConfig", b =>
                {
                    b.Navigation("ScanSessions");
                });

            modelBuilder.Entity("API.Models.Courses", b =>
                {
                    b.Navigation("CourseSubjects");
                });

            modelBuilder.Entity("API.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("DepartmentSubjects");
                });

            modelBuilder.Entity("API.Models.ExamBatch", b =>
                {
                    b.Navigation("ScanSessions");
                });

            modelBuilder.Entity("API.Models.GeneratedPdf", b =>
                {
                    b.Navigation("UploadQueues");
                });

            modelBuilder.Entity("API.Models.Marking", b =>
                {
                    b.Navigation("QuestionMarks");
                });

            modelBuilder.Entity("API.Models.Operator", b =>
                {
                    b.Navigation("ScanSessions");
                });

            modelBuilder.Entity("API.Models.Paper", b =>
                {
                    b.Navigation("ProjectPapers");

                    b.Navigation("Sections");

                    b.Navigation("SubjectPapers");
                });

            modelBuilder.Entity("API.Models.Project", b =>
                {
                    b.Navigation("ProjectPapers");
                });

            modelBuilder.Entity("API.Models.ProjectPaper", b =>
                {
                    b.Navigation("Scripts");
                });

            modelBuilder.Entity("API.Models.Question", b =>
                {
                    b.Navigation("QuestionMarks");
                });

            modelBuilder.Entity("API.Models.ScanSession", b =>
                {
                    b.Navigation("Booklets");

                    b.Navigation("ScannedPages");
                });

            modelBuilder.Entity("API.Models.ScannedPage", b =>
                {
                    b.Navigation("PageEvents");
                });

            modelBuilder.Entity("API.Models.Script", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Markings");
                });

            modelBuilder.Entity("API.Models.Section", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("API.Models.Session", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("API.Models.Subject", b =>
                {
                    b.Navigation("CourseSubjects");

                    b.Navigation("DepartmentSubjects");

                    b.Navigation("ExaminerExpertises");

                    b.Navigation("SubjectPapers");
                });

            modelBuilder.Entity("API.Models.University", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Expertise");

                    b.Navigation("Markings");
                });
#pragma warning restore 612, 618
        }
    }
}
